"""Regenerate RESEARCH_STATUS.md from gate / soak / probe JSON records."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
RESEARCH_DIR = REPO_ROOT / "research" / "solver-assurance-and-gradients"
DEFAULT_STATUS_PATH = RESEARCH_DIR / "RESEARCH_STATUS.md"

GATE_PATHS: dict[str, Path] = {
    "platform_soak_aggregate": REPO_ROOT
    / "output"
    / "research"
    / "multi_host"
    / "aggregate_win_wsl"
    / "platform_soak_aggregate.json",
    "r6_scaffold": RESEARCH_DIR / "reports" / "R6_DECISION_REPORT_SCAFFOLD.json",
    "sampling_study": RESEARCH_DIR / "fixtures" / "sampling_study_ci_small.json",
    "cbf_rh": RESEARCH_DIR / "fixtures" / "cbf_rh_ci_small.json",
    "track1_probe_windows": REPO_ROOT
    / "output"
    / "research"
    / "track1_probe_windows_live"
    / "attestation.json",
    "track1_probe_wsl": REPO_ROOT / "output" / "research" / "track1_probe_wsl_live" / "attestation.json",
}


@dataclass(slots=True)
class GateSnapshot:
    name: str
    path: Path
    present: bool
    summary: dict[str, Any]


def _load_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return raw if isinstance(raw, dict) else None


def collect_gate_snapshots(paths: dict[str, Path] | None = None) -> list[GateSnapshot]:
    mapping = paths or GATE_PATHS
    out: list[GateSnapshot] = []
    for name, path in mapping.items():
        data = _load_json(path)
        summary: dict[str, Any] = {}
        if data is not None:
            if name == "platform_soak_aggregate":
                summary = {
                    "schema_id": data.get("schema_id"),
                    "r4_multi_host_gate_ready": data.get("r4_multi_host_gate_ready"),
                    "historical_r4_multi_host_gate_ready": data.get("historical_r4_multi_host_gate_ready"),
                    "historical_structural_gate_ready": data.get("historical_structural_gate_ready"),
                    "promotion_eligible": data.get("promotion_eligible", False),
                    "invalidation_reason": data.get("invalidation_reason"),
                    "n_real_hosts": data.get("n_real_hosts"),
                    "n_synthetic_hosts": data.get("n_synthetic_hosts"),
                }
            elif name.startswith("track1_probe"):
                summary = {
                    "schema_id": data.get("schema_id"),
                    "succeeded": data.get("succeeded"),
                    "reduce_watermarks": data.get("reduce_watermarks"),
                }
            elif name == "r6_scaffold":
                gate = data.get("flagship_gate") if isinstance(data.get("flagship_gate"), dict) else {}
                summary = {
                    "schema_id": data.get("schema_id"),
                    "decision_status": data.get("decision_status") or data.get("status"),
                    "blocked": (data.get("decision_status") or "BLOCKED") == "BLOCKED",
                    "execution_authorized": bool(data.get("execution_authorized")),
                    "flagship_gate_passed": bool(gate.get("passed")),
                    "document_version": data.get("document_version"),
                }
            else:
                summary = {
                    "schema_id": data.get("schema_id"),
                    "keys": sorted(list(data.keys()))[:12],
                }
        out.append(GateSnapshot(name=name, path=path, present=data is not None, summary=summary))
    return out


def render_research_status(snapshots: list[GateSnapshot] | None = None) -> str:
    snaps = snapshots if snapshots is not None else collect_gate_snapshots()
    by_name = {s.name: s for s in snaps}
    agg = by_name.get("platform_soak_aggregate")
    r4_ready = False
    invalidation = "pre_v1_digest_semantics;awaiting_r12_multihost_rebuild"
    hist_ready = None
    if agg and agg.present:
        r4_ready = bool(agg.summary.get("r4_multi_host_gate_ready"))
        invalidation = str(agg.summary.get("invalidation_reason") or invalidation)
        hist_ready = agg.summary.get("historical_r4_multi_host_gate_ready")
        if hist_ready is None:
            hist_ready = agg.summary.get("historical_structural_gate_ready")

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Research status (Track 2) — evidence rebuild Phase 0 / R9",
        "",
        f"Generated by `conicshield.experimental.assurance.status_report` at `{generated}`.",
        "Claims below are derived from on-disk gate records — not hand-maintained promotion text.",
        "",
        "**No production promotion claimed.** Assurance schema current: `research.assurance_bundle.v1`.",
        "",
        "## Gate records (machine-read)",
        "",
        "| Record | Present | Key fields |",
        "| ------ | ------- | ---------- |",
    ]
    for s in snaps:
        key_bits = ", ".join(f"{k}={v!r}" for k, v in list(s.summary.items())[:6]) if s.present else "(missing)"
        rel = s.path.as_posix().replace(REPO_ROOT.as_posix() + "/", "")
        lines.append(f"| `{s.name}` (`{rel}`) | {'yes' if s.present else 'no'} | {key_bits} |")

    lines.extend(
        [
            "",
            "## Promotion gates (honest, from records)",
            "",
            "| Gate | Status |",
            "| ---- | ------ |",
            "| R1 advanced sampling → production | **Not passed** (research study fixtures exist; production not claimed) |",
            "| R2 observatory / native grads | **Not passed** (experimental paths only; production `differentiation_api=False`) |",
            "| R3 frontiers publication-grade | **Partial / host-local** — do not elevate without S4 live attestation |",
            (
                f"| R4 proof-carrying flagship | **Not passed** — `r4_multi_host_gate_ready={r4_ready}` "
                f"(invalidated: `{invalidation}`"
                + (f"; historical_structural={hist_ready!r}" if hist_ready is not None else "")
                + ") |"
            ),
            "| R5 CBF stage-4 RH | Checklist fixtures present; experimental RH only; **not** production-qualified |",
            "| R6 training | **BLOCKED** until R14 flagship promotion gate passes (harness structure only; no results) |",
            "",
            "## Evidence rebuild notes",
            "",
            "- Phase 0 invalidated promotion use of prior multi-host aggregates and synthetic sensitivity soaks.",
            "- Historical soak artifacts are preserved under deprecated schema ids with `invalidation_reason`.",
            "- `assurance_bundle` v1 requires full SHA-256 digests, three-valued verification, and recomputing machine checks.",
            "- L3 requires live sensitivity (not manual `jacobian_norm`); L4 requires governed manifest + multi-host qualification (R12).",
            "- L4 is numerical assurance, **not** a system-level safety proof.",
            "- R14 flagship candidate: `ProofCarryingProjection` + `evaluate_flagship_promotion_gate` (fail-closed; numerical evidence ≠ system safety).",
            "- R15 wires R6 authorization through the flagship gate; intervention-frequency reduction alone is not promotion evidence.",
            "",
            "## Explicit non-claims",
            "",
            "- Experimental modules are **not** in stable `conicshield.__all__`.",
            "- No production API / claims / backends / release policy / governed benchmark changes.",
            "- No R6 training execution while the flagship gate fails.",
            "- Numerical assurance / flagship predicates are not system-level safety proof.",
            "- `r4_multi_host_gate_ready=true` must not appear as a current promotable claim while invalidation is in force.",
            "",
        ]
    )
    return "\n".join(lines)


def write_research_status(*, path: Path | None = None) -> Path:
    out = path or DEFAULT_STATUS_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_research_status(), encoding="utf-8")
    return out


def main() -> None:
    import argparse

    from conicshield.experimental.assurance.platform_soak import invalidate_on_disk_soak_artifacts

    parser = argparse.ArgumentParser(description="Regenerate RESEARCH_STATUS.md from gate records")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_STATUS_PATH,
        help="Path to write RESEARCH_STATUS.md",
    )
    parser.add_argument(
        "--invalidate-soaks",
        type=Path,
        default=REPO_ROOT / "output" / "research" / "multi_host",
        help="Annotate historical soak artifacts under this root (skip if missing)",
    )
    parser.add_argument("--skip-invalidate", action="store_true")
    args = parser.parse_args()
    if not args.skip_invalidate and args.invalidate_soaks is not None:
        touched = invalidate_on_disk_soak_artifacts(args.invalidate_soaks)
        print(f"annotated {len(touched)} soak artifacts")
    path = write_research_status(path=args.output)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
